version: "3.8"

services:
  s3-ceph-tool:
    image: nasfong/s3-ceph-tool:production
    container_name: s3-ceph-tool
    ports:
      - "3000:80"
    environment:
      NEXT_PUBLIC_KEYCLOAK_URL: https://sso.sabay.com
      NEXT_PUBLIC_KEYCLOAK_REALM: cloud
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: cloud_user
      NEXT_PUBLIC_GATEWAY_URL: https://gateway.sabay.com/graphql
      NEXT_PUBLIC_S3_ENDPOINT: https://fsgw.sabay.com
      NEXT_PUBLIC_CERTIFICATE: true